services:
  api:
    build: .
    container_name: intervue-api
    ports:
      - "8000:8000"

    env_file:
      - .env

    depends_on:
      - redis

    environment:
      REDIS_URL: redis://redis:6379

    volumes:
      - .:/app

    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: intervue-redis

    ports:
      - "6379:6379"

    command: redis-server --appendonly yes

    volumes:
      - redis_data:/data

    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: intervue-prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: intervue-grafana

    ports:
      - "3001:3000"

    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin

    volumes:
      - grafana_data:/var/lib/grafana

    restart: unless-stopped

volumes:
  redis_data:
  grafana_data: